template = "https://github.com/giellalt/template-lang-und"
rev_id = 257
template_sha = "0b3fb3d8836831dedcfe3f4b9fcdc3e2aef12fa5"

[replacements]
__GLOTTOLOG_ID__ = "hili1240"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-hil"
__UND2C__ = "hil"
__UNDEFINED__ = "Hiligaynon"
__UND__ = "hil"
